[project]
name = "edtrace"
version = "0.2.0"
description = "Library for tracing through Python programs for educational presentation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "requests",
    "beautifulsoup4",
]

[project.optional-dependencies]
# Needed to @inspect torch tensors / sympy expressions
torch = ["torch"]
sympy = ["sympy"]
